<a href="https://colab.research.google.com/github/Mayank-iitp/androidStudio1/blob/main/fakenewsclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/fkenews.csv', encoding='latin1')

In [ ]:
df.head()

id                                          Statement  \
0   2  WHO praises India's Aarogya Setu app, says it ...   
1   3  In Delhi, Deputy US Secretary of State Stephen...   
2   4  LAC tensions: China's strategy behind delibera...   
3   5  India has signed 250 documents on Space cooper...   
4   6  Tamil Nadu chief minister's mother passes away...   

                                               Image       Web  Category  \
0  https://cdn.dnaindia.com/sites/default/files/s...  DNAINDIA  COVID-19   
1  https://cdn.dnaindia.com/sites/default/files/s...  DNAINDIA  VIOLENCE   
2  https://cdn.dnaindia.com/sites/default/files/s...  DNAINDIA    TERROR   
3  https://cdn.dnaindia.com/sites/default/files/s...  DNAINDIA  COVID-19   
4  https://cdn.dnaindia.com/sites/default/files/s...  DNAINDIA  ELECTION   

     Date  Label  
0  Oct-20      0  
1  Oct-20      0  
2  Oct-20      0  
3  Oct-20      0  
4  Oct-20      0

In [ ]:
df= df.drop(["Image","Date","id","Category"],axis=1)

In [ ]:
df.head()

Statement       Web  Label
0  WHO praises India's Aarogya Setu app, says it ...  DNAINDIA      0
1  In Delhi, Deputy US Secretary of State Stephen...  DNAINDIA      0
2  LAC tensions: China's strategy behind delibera...  DNAINDIA      0
3  India has signed 250 documents on Space cooper...  DNAINDIA      0
4  Tamil Nadu chief minister's mother passes away...  DNAINDIA      0

In [ ]:
df["Label"].dtype

dtype('int64')

In [ ]:
df.tail()

Statement         Web  Label
56709  Fact Check: This is not Bruce Lee playing ping...  INDIATODAY      1
56710  Fact Check: Did Japan construct this bridge in...  INDIATODAY      1
56711  Fact Check: Viral video of Mexico earthquake i...  INDIATODAY      1
56712  Fact Check: Ballet performance by Chinese coup...  INDIATODAY      1
56713  Fact Check: Is this little boy crossing into J...  INDIATODAY      1

In [ ]:
df["Label"].value_counts()

Label
0    37800
1    18914
Name: count, dtype: int64

In [ ]:
from sklearn.utils import resample

In [ ]:
true= df[df["Label"]==0]
false= df[df["Label"]==1]

In [ ]:
num_sample=len(false)
undersample= resample(true, replace= False, n_samples= num_sample, random_state= 9)

In [ ]:
df= pd.concat([undersample,false])

In [ ]:
df.head()

Statement            Web  Label
6924   ÔInduction of Rafale important given the kind ...    THESTATEMAN      0
17495  Atmanirbhar Bharat 3 announcement headline man...   TRIBUNEINDIA      0
4405   Kerala: Former PWD minister Ebrahim Kunju arre...  INDIANEXPRESS      0
7480   Anchal Gangwal, tea sellerÕs daughter becomes ...    THESTATEMAN      0
15253  COVID-19: Health Ministry issues guidelines fo...   TRIBUNEINDIA      0

In [ ]:
df.reset_index(drop= True,inplace= True)

In [ ]:
df.head()

Statement            Web  Label
0  ÔInduction of Rafale important given the kind ...    THESTATEMAN      0
1  Atmanirbhar Bharat 3 announcement headline man...   TRIBUNEINDIA      0
2  Kerala: Former PWD minister Ebrahim Kunju arre...  INDIANEXPRESS      0
3  Anchal Gangwal, tea sellerÕs daughter becomes ...    THESTATEMAN      0
4  COVID-19: Health Ministry issues guidelines fo...   TRIBUNEINDIA      0

In [ ]:
df["content"]= df['Statement']+" "+df["Web"]

In [ ]:
X= df.drop(["Web","Label","Statement"],axis=1)

In [ ]:
df.head()

Statement            Web  Label  \
0  ÔInduction of Rafale important given the kind ...    THESTATEMAN      0   
1  Atmanirbhar Bharat 3 announcement headline man...   TRIBUNEINDIA      0   
2  Kerala: Former PWD minister Ebrahim Kunju arre...  INDIANEXPRESS      0   
3  Anchal Gangwal, tea sellerÕs daughter becomes ...    THESTATEMAN      0   
4  COVID-19: Health Ministry issues guidelines fo...   TRIBUNEINDIA      0   

                                             content  
0  ÔInduction of Rafale important given the kind ...  
1  Atmanirbhar Bharat 3 announcement headline man...  
2  Kerala: Former PWD minister Ebrahim Kunju arre...  
3  Anchal Gangwal, tea sellerÕs daughter becomes ...  
4  COVID-19: Health Ministry issues guidelines fo...

In [ ]:
X.head()

content
0  ÔInduction of Rafale important given the kind ...
1  Atmanirbhar Bharat 3 announcement headline man...
2  Kerala: Former PWD minister Ebrahim Kunju arre...
3  Anchal Gangwal, tea sellerÕs daughter becomes ...
4  COVID-19: Health Ministry issues guidelines fo...

In [ ]:
Y= df["Label"]

In [ ]:
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Label, dtype: int64

In [ ]:
Y.shape

(37828,)

In [ ]:
Y.head()
Y.value_counts()

Label
0    18914
1    18914
Name: count, dtype: int64

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size= 10000

In [ ]:
mess= X.copy()

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
mess["content"][1]

'Atmanirbhar Bharat 3 announcement headline management: Congress TRIBUNEINDIA'

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(mess)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', mess["content"][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
32828
32829
32830
32831
32832
32833
32834
32835
32836
32837
32838
32839
32840
32841
32842
32843
32844
32845
32846
32847
32848
32849
32850
32851
32852
32853
32854
32855
32856
32857
32858
32859
32860
32861
32862
32863
32864
32865
32866
32867
32868
32869
32870
32871
32872
32873
32874
32875
32876
32877
32878
32879
32880
32881
32882
32883
32884
32885
32886
32887
32888
32889
32890
32891
32892
32893
32894
32895
32896
32897
32898
32899
32900
32901
32902
32903
32904
32905
32906
32907
32908
32909
32910
32911
32912
32913
32914
32915
32916
32917
32918
32919
32920
32921
32922
32923
32924
32925
32926
32927
32928
32929
32930
32931
32932
32933
32934
32935
32936
32937
32938
32939
32940
32941
32942
32943
32944
32945
32946
32947
32948
32949
32950
32951
32952
32953
32954
32955
32956
32957
32958
32959
32960
32961
32962
32963
32964
32965
32966
32967
32968
32969
32970
32971
32972
32973
32974
32975
32976
32977
32978
32979
32980
32981
32982
32983
32984
32985
3

In [ ]:
corpus

['induct rafal import given kind situat border rajnath singh thestateman',
 'atmanirbhar bharat announc headlin manag congress tribuneindia',
 'kerala former pwd minist ebrahim kunju arrest palarivattom flyover graft case indianexpress',
 'anchal gangwal tea seller daughter becom iaf pilot thestateman',
 'covid health ministri issu guidelin dental clinic tribuneindia',
 'book lockdown violat gold digger saint funer kanpur thestateman',
 'cbi put hathra case fir websit remov within hour tribuneindia',
 'bjp slam congress silenc agustawestland alleg indianexpress',
 'cisf post local languag vers personnel airport reject kanimozhi charg tribuneindia',
 'congress b k hariprasad opposit nomine rs deputi chairman post sourc theprint',
 'tech mahindra sack divers offic mock gay peopl call islam global pain theprint',
 'cm kejriw oppos l g order day institut quarantin covid patient delhi thestateman',
 'caa unnecessari though india intern matter bangladesh pm sheikh hasina thestateman',
 'pm m

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[7354, 5967, 581, 3133, 8748, 4711, 1731, 9465, 6145, 840],
 [1625, 9228, 7768, 2068, 5021, 3445, 3513],
 [2693, 7741, 4364, 3019, 8443, 369, 8100, 3672, 8002, 2870, 3656, 8322],
 [1990, 1456, 6580, 2549, 91, 7088, 1384, 4726, 840],
 [9402, 4950, 9536, 5568, 3458, 1458, 254, 3513],
 [5811, 1141, 9845, 3212, 7268, 7923, 8155, 7242, 840],
 [5546, 9141, 8103, 3656, 9400, 2754, 9897, 8051, 2506, 3513],
 [301, 7334, 3445, 3452, 3555, 5854, 8322],
 [5274, 1802, 4864, 7755, 2095, 1858, 4963, 6039, 3861, 5991, 3513],
 [3445, 7949, 102, 2249, 3294, 7984, 5829, 108, 8154, 1802, 3404, 1267],
 [7, 1433, 6869, 8782, 4801, 5764, 9002, 6790, 9578, 1352, 5737, 3367, 1267],
 [7102, 771, 9489, 7079, 3888, 2843, 7211, 587, 2566, 9402, 1678, 9038, 840],
 [5102, 5492, 1265, 2145, 9168, 8672, 2384, 8, 9793, 1184, 840],
 [8, 6761, 1601, 8469, 1363, 7457, 3900, 8865, 2369, 3888, 1558, 7526],
 [1090, 9593, 5095, 4855, 2124, 2542, 8054, 5518, 1267],
 [6824,
  7586,
  1733,
  8127,
  2040,
  8448,
  8142,
  126

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)



[[   0    0    0 ... 9465 6145  840]
 [   0    0    0 ... 5021 3445 3513]
 [   0    0    0 ... 2870 3656 8322]
 ...
 [   0    0    0 ... 8350 5483 6877]
 [   0    0    0 ... 9766 5161 6877]
 [   0    0    0 ... 1145 1293 6877]]


In [ ]:
from tensorflow.keras.layers import Dropout

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            400000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 456501 (1.74 MB)
Trainable params: 456501 (1.74 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=49)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
396/396 [==============================] - 19s 43ms/step - loss: 0.1486 - accuracy: 0.9367 - val_loss: 0.0354 - val_accuracy: 0.9895
Epoch 2/10
396/396 [==============================] - 18s 45ms/step - loss: 0.0218 - accuracy: 0.9925 - val_loss: 0.0301 - val_accuracy: 0.9893
Epoch 3/10
396/396 [==============================] - 17s 42ms/step - loss: 0.0110 - accuracy: 0.9962 - val_loss: 0.0373 - val_accuracy: 0.9893
Epoch 4/10
396/396 [==============================] - 16s 41ms/step - loss: 0.0064 - accuracy: 0.9983 - val_loss: 0.0370 - val_accuracy: 0.9892
Epoch 5/10
396/396 [==============================] - 17s 43ms/step - loss: 0.0050 - accuracy: 0.9987 - val_loss: 0.0407 - val_accuracy: 0.9896
Epoch 6/10
396/396 [==============================] - 17s 42ms/step - loss: 0.0037 - accuracy: 0.9987 - val_loss: 0.0470 - val_accuracy: 0.9883
Epoch 7/10
396/396 [==============================] - 16s 40ms/step - loss: 0.0029 - accuracy: 0.9991 - val_loss: 0.0433 - val_accuracy:

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
import numpy as np

y_pred_binary = np.where(y_pred > 0.5, 1, 0)
confusion_matrix(y_test, y_pred_binary)

391/391 [==============================] - 3s 7ms/step


array([[6078,   42],
       [ 110, 6254]])

y_test data type: <class 'numpy.ndarray'>
y_pred data type: <class 'numpy.ndarray'>


In [ ]:
from sklearn.metrics import accuracy_score
y_pred_binary = np.where(y_pred > 0.5, 1, 0)
accuracy_score(y_test,y_pred_binary)

0.987824415251522

In [ ]:
def preprocess_text(text):
  vocab_size= 10000
  encod_text= [one_hot(text, vocab_size)]
  max_length=20
  padded_text= pad_sequences(encod_text,padding='pre',maxlen=max_length)
  return padded_text

def predict_news(text):
  processed_text= preprocess_text(text)
  prediction= model.predict(processed_text)
  is_fake=(prediction > 0.5).astype(int)

  return bool(is_fake[0])

In [ ]:
text= " india can never overtake china"
isk= predict_news(text)
if isk:
  print("The news is likely to be fake")
else:
  print ("The news is likely to be real")

1/1 [==============================] - 0s 41ms/step
The news is likely to be fake


In [ ]:
import pickle

In [ ]:
filename= "news_classifier.sav"

In [ ]:
pickle.dump(model, open(filename, "wb"))

In [ ]:
loaded_model= pickle.load(open("news_classifier.sav", 'rb'))

In [ ]:
from tensorflow.keras.models import load_model, save_model

In [ ]:
save_model(model, "C:/Users/msing/Documents/newsclassi.keras")

In [ ]:
model.save('path/to/location.keras')